### PR TITLE
Fix face icons and blank banners

### PR DESCRIPTION
**Pull request by FrozenMode**
The face icons are all 256 x 256 now, no more overly large characters or badly centered characters.

As for the banners, all the blank ones have been replaced with the official version. Only issue is that they are 1024 x 512 not 1368 x 675 like the ones before. If that is a problem, I can edit them.

### CODE REVIEW

**Comment by AguzzTN54** [comment]
Looks good! Let me check it out first. 
The banner size doesn’t seem to matter much either, as long as the aspect ratio remains the same.

**Comment by FrozenMode** [comment]
They don't appear to be the same aspect ratio. The ones I've uploaded are 2:1, the ones you have are 152:75.

**Comment by AguzzTN54** [comment]
> They don't appear to be the same aspect ratio. The ones I've uploaded are 2:1, the ones you have are 152:75.

It's fine, it's still tolerable.

**Review by AguzzTN54 — CHANGES_REQUESTED** [review]
Sorry for taking so long, but could you keep Amber, Mona, Jean, and Rosaria? They have two different designs, and your PR replaces it with the old design.
There's also a close-up icon in [outfit's folder](https://github.com/Mantan21/Genshin-Impact-Wish-Simulator/tree/master/src/images/outfits/face) if you don't know.

**Comment by AguzzTN54** [comment]
I'll Merge after these changes

**Comment by FrozenMode** [comment]
Alright, it has been done.

**Review by AguzzTN54 — APPROVED** [review]

**Comment by AguzzTN54** [comment]
Great, thank you so much! It will go live soon.

**Pull request merged**
