### PR TITLE
Add Ukrainian language

### PR DESCRIPTION
**Pull request by dolA-0**
add ukrainian lang

### CODE REVIEW

**Review by AguzzTN54 — CHANGES_REQUESTED** [review]
Good job, but I think there are still quite a few words that haven't been translated yet.
I will merge it with the main branch after at least 80% of the words have been translated.

**Comment by dolA-0** [comment]
> Good job, but I think there are still quite a few words that haven't been translated yet.
> I will merge it with the main branch after at least 80% of the words have been translated.

Ok if I did the translation correctly and the other files correctly. I've just started preparing for exams, so I'm a little short on time now. I will translate if possible.

**Comment by dolA-0** [comment]
> Good job, but I think there are still quite a few words that haven't been translated yet.
> I will merge it with the main branch after at least 80% of the words have been translated.

Ok if I did the translation correctly and the other files correctly. I've just started preparing for exams, so I'm a little short on time now. I will translate if possible.

**Comment by AguzzTN54** [comment]
Sure, no problem, please take your time.

**Pull request closed without merging**
