### PR TITLE
Create es-ES.json

### PR DESCRIPTION
**Pull request by JustCumbreon**
its not finished yet, bit im already translating it and will have it in 2 days at least

### CODE REVIEW

**Comment by AguzzTN54** [comment]
Great, thank you for your contribution, I will look forward to hearing from you.

**Comment by JustCumbreon** [comment]
You're welcome, i'm gonna translate more maybe tomorrow because i have some
exams and i found some free time to do ir, so i'll finish when i have time


Missatge de Agustinus Yohannes ***@***.***> del dia dj., 27
d’oct. 2022 a les 14:03:

**Review by AguzzTN54 — COMMENTED** [review]
Sorry, do you still plan to continue with this translation?

**Review by AguzzTN54 — CHANGES_REQUESTED** [review]
There are still a lot of words that need to be translated.

**Pull request closed without merging**
